# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb0ae7c7030143032924fedfd5979d560e0646f2e69ddec533459523cc8b0cdde6ebb0570e2a5e154a89a880d35e3a9d749f7c53c0e39113132cea46c8ee5a4

test:
  secret_key_base: a594d8b6d6a9600c187c4a014c98c0cd6182c53720b48364e08543dc757e16cc605ba1cef5f2b2c98ec05dea2b4ccc767479e2978bbc58b514f7ad5b2e22339c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
